services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert:/app/cert
    network_mode: "bridge"
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - backend

  redis:
    image: redis
    command: ["redis-server", "--port", "6380"]
    ports:
      - 6380:6380

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  worker:
    build:
      context: backend
      dockerfile: Dockerfile
    command: celery --app app.tasks worker --loglevel=DEBUG -Q main-queue -c 1

  flower:
    image: mher/flower  # Flower monitoring tool for Celery
    ports:
      - "5555:5555"  # Expose Flower's web UI on port 5555
    depends_on:
      - redis  # Wait for Redis to start before Flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6380/0
      - FLOWER_PORT=5555

  backend:
    network_mode: "bridge"
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    env_file:
      - .env  # This will automatically load variables from the .env file
    environment:
      PYTHONPATH: .
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/postgres"
      REDIS_URL: "redis://redis:6380"
    depends_on:
      - "postgres"

volumes:
  db-data:
